---
title: "Mapa de conectividad de grupos funcionales de aves en otros hábitats en el Corredor Biológico Interurbano María Aguilar"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
#-------------------- Paquetes --------------------

library(flexdashboard)
library(dplyr)
library(sf)
library(leaflet)
library(leafem)
library(esri2sf)
library(raster)

#--------------- URL de geoservicios --------------

url_agfs_limite_cbima <-
  "https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_limite_cbi_maria_aguilar/FeatureServer/0"

url_raster_probabilidad_conectividad <-
  "https://raw.githubusercontent.com/atlas-servicios-ecosistemicos-gam/datos-conectividad/master/cbima/otras/PROBABILIDAD_CONECTIVIDAD_OTRAS_MA_WEB.TIF"

url_agfs_teselas <-
  "https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_conectividad_parches_esenciales_importantes_otras_ma/FeatureServer/0"

url_agfs_rutas <-
  "https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_conectividad_rutas_conectividad_otras_ma/FeatureServer/0"

#--------------- Objetos sf y raster ---------------

# Límite del CBIMA
sf_limite_cbima <-
  esri2sf(url_agfs_limite_cbima)

# Límite del CBIMA (reproyectado a Web Mercator)
sf_limite_cbima_web <- 
  sf_limite_cbima %>%
  st_transform(3857)

# Capa raster de probabilidad de conectividad (en Web Mercator)
raster_probabilidad_conectividad <-
  raster(url_raster_probabilidad_conectividad) %>%
  crop(sf_limite_cbima_web) %>%
  mask(sf_limite_cbima_web)

# Teselas
sf_teselas <- 
  esri2sf(url_agfs_teselas)

# Rutas de conectividad
sf_rutas <- 
  esri2sf(url_agfs_rutas)

#---------------- Paletas de colores ---------------

# Esencialidad
bins_esencialidad <- c(0, 0.003047, 0.002421, 0.001170, 0.000578, Inf)
etiquetas_esencialidad <- c("Muy poco esencial", "Poco esencial", "Medianamente esencial", "Esencial", "Altamente esencial")
pal_esencialidad <- 
  colorBin(
    bins = bins_esencialidad,
    palette = c(rgb(247,205,164, maxColorValue=255), rgb(220,136,102, maxColorValue=255),
                rgb(209,83,84,maxColorValue=255),    rgb(160,45,103, maxColorValue=255),
                rgb(103,67,130,maxColorValue=255)), 
    domain = sf_teselas$d_PC,
    n = 5,
  )

# Importancia
bins_importancia <- c(0, 356935791.96, 257802227.21, 112767551.37, 26780965.42, Inf)
etiquetas_importancia <- c("Muy baja importancia", "Importancia baja", "Importancia media", "Alta importancia", "Muy alta importancia")
pal_importancia <- 
  colorBin(
    bins = bins_importancia,
    palette = c(rgb(247,205,164, maxColorValue=255), rgb(220,136,102, maxColorValue=255),
                rgb(209,83,84,maxColorValue=255),    rgb(160,45,103, maxColorValue=255),
                rgb(103,67,130,maxColorValue=255)), 
    domain = sf_teselas$IF_,
    n = 5,
  )

# Probabilidad
colores_probabilidad <- 
  c(rgb(247,205,164, maxColorValue=255), rgb(209,83,84,maxColorValue=255), rgb(103,67,130,maxColorValue=255))
etiquetas_probabilidad <- c("Baja", "Media", "Alta")
pal_probabilidad <- 
  colorNumeric(
    colores_probabilidad, 
    values(raster_probabilidad_conectividad),
    na.color = "transparent"
  )

```

Row
-----------------------------------------------------------------------

### 

```{r}

leaflet() %>%
  addProviderTiles(providers$CartoDB.DarkMatter, group = "CartoDB Dark Matter") %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Stamen Toner Lite") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>%
  addPolygons(
    data = sf_limite_cbima,
    color = "Purple",
    fillColor = "transparent",
    stroke = TRUE,
    weight = 6.0,
    group = "Límite del CBIMA"
  ) %>%
  addRasterImage(
    raster_probabilidad_conectividad, 
    colors = pal_probabilidad,
    opacity = 0.9,
    group = "Probabilidad de conectividad"
  ) %>%  
  addLegend(
    title = "Probabilidad de conectividad", 
    values = values(raster_probabilidad_conectividad),
    colors = colores_probabilidad,
    labels = etiquetas_probabilidad,
    position = "bottomright",
    group = "Probabilidad de conectividad"
  ) %>%  
  addPolygons(
    data = sf_teselas,
    fillOpacity = 0.9,
    stroke = TRUE,
    color = "Black",
    fillColor = ~pal_esencialidad(d_PC),
    weight = 1,
    group = "Teselas esenciales"
  ) %>%
  addLegend(
    position = "bottomright",
    pal = pal_esencialidad,
    values = sf_teselas$d_PC,
    labFormat = function(type, cuts, p) {paste0(etiquetas_esencialidad)},
    group = "Teselas esenciales",
    title = "Esencialidad"
  ) %>%    
  addPolygons(
    data = sf_teselas,
    fillOpacity = 0.9,
    stroke = TRUE,
    color = "Black",
    fillColor = ~pal_importancia(IF_),
    weight = 1,
    group = "Teselas importantes"
  ) %>%
  addLegend(
    position = "bottomright",
    pal = pal_importancia,
    values = sf_teselas$IF_,
    labFormat = function(type, cuts, p) {paste0(etiquetas_importancia)},
    group = "Teselas importantes",
    title = "Importancia"
  ) %>%    
  addPolylines(
    data = sf_rutas,
    color = "Green",
    fillColor = "transparent",
    stroke = TRUE,
    weight = 1.5,
    group = "Rutas de conectividad"
  ) %>%
  addLayersControl(
    baseGroups = c("CartoDB Dark Matter", "OpenStreetMap", "Stamen Toner Lite", "Imágenes de ESRI"),
    overlayGroups = c("Límite del CBIMA", "Probabilidad de conectividad", "Teselas esenciales", "Teselas importantes", "Rutas de conectividad"),
    options = layersControlOptions(collapsed = TRUE)    
  ) %>%  
  addMiniMap(
    toggleDisplay = TRUE,
    position = "bottomleft",
    tiles = providers$CartoDB.DarkMatter
  ) %>%
  addScaleBar(
    position = "bottomleft",
    options = scaleBarOptions(imperial = FALSE)
  ) %>%
  addMouseCoordinates() %>%
  hideGroup("Teselas esenciales") %>%
  hideGroup("Teselas importantes")

```